[workspace]
channels = ["conda-forge"]
name = "pycameleon"
platforms = ["osx-arm64", "linux-64"]
version = "0.1.0"

[tasks]
develop = "maturin develop --uv"

[dependencies]
python = "3.12.*"
maturin = ">=1.9.4,<2"
numba = ">=0.61.2,<0.62"
napari = ">=0.6.4,<0.7"
pyqt = ">=5.15.11,<6"
rerun-sdk = ">=0.24.1,<0.25"
marimo = ">=0.17.0,<0.18"
ruff = ">=0.14.2,<0.15"
zig = ">=0.15.1,<0.16"

[pypi-dependencies]
opencv-python = ">=4.12.0.88, <5"
rerun-sdk = { version = "*", extras = ["notebook"] }
maturin = { version = "*", extras = ["zig"] }
