[workspace]
channels = ["conda-forge"]
name = "pycameleon"
platforms = ["osx-arm64", "linux-64"]
version = "0.1.0"

[tasks]
develop = "maturin develop --uv"

[dependencies]
python = ">=3.13.9,<3.14"
maturin = ">=1.9.6,<2"
numba = ">=0.62.1,<0.63"
napari = ">=0.6.6,<0.7"
pyqt = ">=5.15.11,<6"
rerun-sdk = ">=0.26.2,<0.27"
marimo = ">=0.17.7,<0.18"
ruff = ">=0.14.3,<0.15"
zig = ">=0.15.1,<0.16"

[pypi-dependencies]
opencv-python = ">=4.11.0.86, <5"
rerun-sdk = { version = "*", extras = ["notebook"] }
maturin = { version = "*", extras = ["zig"] }
